Ipuch/bioNC

- tests/test_natural_segment.py
First test for the natural segment class.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ipuch/bionc/2)
> new test for natural segment class

- bionc/utils/natural_accelerations.py
- bionc/utils/natural_coordinates.py
- bionc/utils/natural_velocities.py
- tests/test_natural_coordinates.py
fixing it right
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ipuch/bionc/8)
> fixing v, there was a sign mistake

- bionc/__init__.py
- bionc/model_computations/__init__.py
- tests/test_marker.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ipuch/bionc/10)
> Test SegmentMarker Class

- bionc/model_computations/biomechanical_model.py
- bionc/model_computations/natural_segment.py
- bionc/utils/natural_accelerations.py
- bionc/utils/natural_coordinates.py
- bionc/utils/natural_velocities.py
- examples/forward_dynamics.py
- tests/test_biomech_model.py
- tests/test_natural_coordinates.py
- tests/test_natural_velocities.py
Linked to the issue #15 
As I understood it, it was only necessary to do it for function not classes and I chose to do it also on function with Qdot : 
For example TestQdot would become test_qdot even if q tend to be in majuscule.
Hope it work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ipuch/bionc/22)
> Snake case prb

- bionc/bionc_casadi/natural_accelerations.py
- bionc/bionc_casadi/natural_coordinates.py
- bionc/bionc_casadi/natural_velocities.py
- tests/test_natural_coordinates_casadi.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ipuch/bionc/39)
> symbolic vectors

- bionc/bionc_casadi/joint.py
- bionc/bionc_numpy/joint.py
- bionc/model_creation/biomechanical_model_template.py
- bionc/protocols/biomechanical_model.py
- bionc/protocols/joint.py
- tests/test_joints.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ipuch/bionc/45)
> generic interface of joints now can add revolute, hinge and spherical joints

- examples/forward_dynamics/forward_dynamics.py
- tests/test_forward_dynamics.py
go
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ipuch/bionc/46)
> testing forward

- bionc/bionc_casadi/biomechanical_model.py
- bionc/bionc_casadi/natural_segment.py
- bionc/bionc_numpy/biomechanical_model.py
- bionc/bionc_numpy/natural_segment.py
- bionc/protocols/biomechanical_model.py
- bionc/protocols/natural_segment.py
- bionc/utils/inverse_kinematics.py
- examples/forward_dynamics/n_link_pendulum.py
- examples/forward_dynamics/pendulum.py
- examples/forward_dynamics/viz.py
- tests/test_biomech_model.py
- tests/test_natural_segment.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ipuch/bionc/58)
> properties of objects, withdraw parenthesis

- bionc/bionc_casadi/joint.py
- bionc/bionc_casadi/natural_segment.py
- bionc/bionc_numpy/joint.py
- bionc/bionc_numpy/natural_segment.py
- bionc/protocols/biomechanical_model.py
- bionc/protocols/joint.py
- bionc/protocols/natural_segment.py
- examples/forward_dynamics/pendulum.py
- tests/test_biomech_model.py
- tests/test_graph.py
- tests/test_joints.py
- tests/test_natural_coordinates.py
- tests/test_natural_coordinates_casadi.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/59)
> properties, and model graphs

- .github/workflows/run_tests.yml
- bionc/bionc_casadi/biomechanical_model.py
- bionc/bionc_casadi/external_force.py
- bionc/bionc_numpy/biomechanical_model.py
- examples/play_with_joints/two_constant_length.py
docstrings and external forces
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/68)
> doctstrings and external forces

- bionc/model_creation/biomechanical_model_template.py
- examples/model_creation/right_side_lower_limb.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/78)
> Add feature :  Add new argument in add_model to be able to use constant lenght joint

- bionc/model_creation/natural_axis_template.py
- tests/test_natural_axis_template.py
Some function have been added to be able to construct model using vector instead of point. Not sure if they were positionned in the correct function and if these function might have alredy existed in the code but I did not find them. 
The inspiration is from the static function in marker_template. If the function are ok. I can eventually add some testing in from it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/89)
> Add some static function to construct some model with cross product of axis

- bionc/model_creation/marker_template.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/93)
> [RTR] Some docstring modification

- .github/workflows/run_tests.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/97)
> Code cov not working removing it for now.

- bionc/protocols/biomechanical_model.py
- bionc/protocols/natural_coordinates.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/102)
> more generic methods

- examples/inverse_kinematics/inverse_kinematics.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/109)
> update example ik

- .github/workflows/run_tests.yml
- bionc/bionc_numpy/inverse_kinematics.py
- bionc/utils/constants.py
yes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/119)
> defining constant like a pro

- tests/test_graph.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/121)
> apparently its better formatted like this.

- bionc/bionc_casadi/biomechanical_model_joints.py
- bionc/bionc_numpy/biomechanical_model_joints.py
- bionc/protocols/biomechanical_model.py
- bionc/protocols/biomechanical_model_joints.py
- bionc/protocols/natural_segment.py
- tests/test_is_ground.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/126)
> less complexity as always.

- bionc/bionc_casadi/natural_coordinates.py
- bionc/bionc_casadi/natural_inertial_parameters.py
- bionc/bionc_numpy/natural_coordinates.py
- bionc/bionc_numpy/natural_inertial_parameters.py
- bionc/utils/transformation_matrix.py
- tests/test_transformation_matrix.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/135)
> refactor( for less complexity when reading)

- README.md
- #136
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/138)
> How to cite README.md 

- .github/workflows/run_tests.yml
- bionc/bionc_numpy/generalized_force.py
- bionc/bionc_numpy/inverse_kinematics.py
- tests/test_ultimate_inverse_kinematics.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/139)
> small refactor and typo

- bionc/bionc_numpy/inverse_kinematics.py
- tests/test_initial_guess_mode.py
- tests/test_initial_guess_mode_no_marker.py
- tests/test_ultimate_inverse_kinematics_heatmap.py
yoga
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/142)
> refactor: inverse kinematics init

- bionc/bionc_numpy/inverse_kinematics.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/143)
> missing extra commit

- bionc/vizualization/pyorerun_interface.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Ipuch/bioNC/151)
> fix: extra viz mass check
